require('dotenv').config()
const nodemailer = require('nodemailer');
const path = require('path');
const { emailList } = require('./emailList');
const { getTextBody, frontnendTemplate } = require('./utils');


// Create a transporter using your Gmail credentials and App Password
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'aamirhannansde@gmail.com',  // Your Gmail address
        pass: process.env.APP_PASSWORD,      // App password generated by Google
    }
});


// Array of recipient emails
const dataList = emailList
// console.log(dataList)



// const dataList = [
//     { email: "aamirhannan08@gmail.com" },
// ]

// Email content
const mailOptions = {
    from: 'aamirhannansde@gmail.com',  // sender address
    subject: 'Application for full stack developer',  // Subject line
    text: '',  // plain text body
    attachments: [
        {
            filename: 'Aamir_Hannan_Resume.pdf', // Name of the file as it will appear in the email
            path: path.join(__dirname, 'Aamir_Hannan_Resume.pdf'), // Path to the PDF file
        }
    ]
};


// Function to send email to all addresses in the array
async function sendEmails() {
    for (let email of dataList) {
        // console.log("email", email)
        try {
            // Set the recipient for each email in the loop
            mailOptions.to = email.email;
            mailOptions.html = getTextBody(email?.name);

            // Send the email
            const info = await transporter.sendMail(mailOptions);
            console.log(`Email sent to ${email.email}: ` + info.response);
        } catch (error) {
            console.log(`Error sending email to ${email}: ` + error);
        }
    }
}

// Call the function to send emails
sendEmails();
